#include "Sort.h"
int main()
{
	int a[] = { 1, 4, 5, 2, 3, 6, 9, 7, 8 };
	int size = sizeof(a) / sizeof(a[0]);
	printf("÷±Ω”≤Â»Î≈≈–Ú:");
	insertSort(a, size);
	print(a, size);
	printf("\n");
	printf("œ£∂˚≈≈–Ú:");
	shellSort(a, size);
	print(a, size);
	printf("\n");
	printf("ºÚµ•—°‘Ò≈≈–Ú1:");
	selectSort1(a, size);
	print(a, size);
	printf("\n");
	printf("ºÚµ•—°‘Ò≈≈–Ú2:");
	selectSort2(a, size);
	print(a, size);
	printf("\n");
	printf("ºÚµ•—°‘Ò≈≈–Ú3:");
	selectSort3(a, size);
	print(a, size);
	printf("\n");
	printf("∂—≈≈–Ú:");
	HeapSort(a, size);
	print(a, size);
	printf("\n");
	printf("øÏÀŸ≈≈–Ú:");
	quickSort(a, size);
	print(a, size);
	printf("\n");
	printf("øÏÀŸ≈≈–Ú∑«µ›πÈ:");
	quickSortNOR(a, size);
	print(a, size);
	printf("\n");
	printf("√∞≈›≈≈–Ú:");
	bubbleSort(a, size);
	print(a, size);
	printf("\n");
	printf("πÈ≤¢≈≈–Ú:");
	MergeSort(a, size);
	print(a, size);
	printf("\n");
	printf("º∆ ˝≈≈–Ú:");
	countSort(a, size);
	print(a, size);
	printf("\n");
	system("pause");
	return 0;
}